### ISSUE TITLE
feat: Fallback for older browsers

### ISSUE THREAD

**Issue by csshugs** [csshugs/FluidMS#4]
Browsers that don’t support custom properties are completely locked out. The generated font-size and line-height declarations are simply ignored and the browser default styles are inherited. This can lead to very inappropriate font-sizes for certain elements.

We should try to find a sensible fallback solution that can be enabled via a Sass feature flag, that provides at least some sort of reasonable font-size declaration for older browsers.

**Comment by fuhlig** [comment]
How would a fallback look like?
Static values as fallbacks for custom properties?

PostCSS could be utilized here to add the static values in postprocess in order to keep the mixins simpler.
This could also use globally set browser-support (via [browserlist](https://browserl.ist))

**Comment by csshugs** [comment]
> Static values as fallbacks for custom properties?

Yes, that’s what I thought. Generate an output that looks something like this:

```css
h1 {
    font-size: 1.77156rem;
    font-size: calc(var(--ms6-ratio) * 1rem);
    line-height: 1.5;
    line-height: var(--ms6-line-height); 
}
```

PostCSS could very well be used, but I’m not sure if we should bake that into FluidMS, as this is mostly implementation-specific.
